export interface Game {
  id: string;
  name: string;
  slug: string;
  description: string;
  thumbnail: string;
  bannerImage: string;
  category: 'slots' | 'casino' | 'skill' | 'bingo' | 'poker' | 'novoline';
  provider: string;
  isFeatured: boolean;
  isNew: boolean;
  isPopular: boolean;
  minBet: number;
  maxBet: number;
  jackpot?: number;
  rtp?: number;
  volatility?: 'low' | 'medium' | 'high';
  features?: string[];
  paylines?: number;
  reels?: number;
  downloadLink?: string;
  
  // Blog Content Fields
  gameOverview?: string;
  howToPlay?: string;
  tipsAndStrategies?: string[];
  gameHistory?: string;
  howToCreateAccount?: string;
  conclusion?: string;
  faqs?: Array<{ question: string; answer: string }>;
  howToDownloadAndInstall?: string;
}

export const gamesData: Game[] = [
  // SLOTS - Popular Novoline Games
  {
    id: 'book-of-ra',
    name: 'Book of Ra',
    slug: 'book-of-ra',
    description: 'Embark on an Egyptian adventure and uncover ancient treasures in this legendary slot.',
    thumbnail: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 5000,
    jackpot: 50000,
    rtp: 96.21,
    volatility: 'high',
    features: ['Free Spins', 'Expanding Symbols', 'Gamble Feature'],
    paylines: 9,
    reels: 5
  },
  {
    id: 'lucky-ladys-charm',
    name: "Lucky Lady's Charm",
    slug: 'lucky-ladys-charm',
    description: 'Let the lucky lady guide you to fortune with magical charms and big wins.',
    thumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 3000,
    jackpot: 30000,
    rtp: 95.02,
    volatility: 'medium',
    features: ['Free Spins', 'Multiplier', 'Wild Symbol'],
    paylines: 10,
    reels: 5
  },
  {
    id: 'sizzling-hot',
    name: 'Sizzling Hot',
    slug: 'sizzling-hot',
    description: 'Classic fruit slot with sizzling hot wins and traditional gameplay.',
    thumbnail: 'https://images.unsplash.com/photo-1596838132731-3301c3a431be?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1596838132731-3301c3a431be?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 2000,
    jackpot: 20000,
    rtp: 95.66,
    volatility: 'low',
    features: ['Scatter Wins', 'Classic Symbols'],
    paylines: 5,
    reels: 5
  },
  {
    id: 'dolphins-pearl',
    name: "Dolphin's Pearl",
    slug: 'dolphins-pearl',
    description: 'Dive into the ocean depths and discover pearls of great value.',
    thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 4000,
    jackpot: 40000,
    rtp: 95.13,
    volatility: 'medium',
    features: ['Free Spins', 'Multiplier', 'Wild Symbol'],
    paylines: 10,
    reels: 5
  },
  {
    id: 'lord-of-the-ocean',
    name: 'Lord of the Ocean',
    slug: 'lord-of-the-ocean',
    description: 'Rule the underwater kingdom and claim legendary treasures.',
    thumbnail: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 5000,
    jackpot: 50000,
    rtp: 95.10,
    volatility: 'high',
    features: ['Free Spins', 'Expanding Symbols', 'Gamble'],
    paylines: 10,
    reels: 5
  },
  {
    id: 'book-of-ra-deluxe',
    name: 'Book of Ra Deluxe',
    slug: 'book-of-ra-deluxe',
    description: 'The enhanced version of the legendary Egyptian adventure slot.',
    thumbnail: 'https://images.unsplash.com/photo-1503917988258-f87a78e3c995?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1503917988258-f87a78e3c995?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: true,
    isNew: true,
    isPopular: true,
    minBet: 10,
    maxBet: 10000,
    jackpot: 100000,
    rtp: 95.10,
    volatility: 'high',
    features: ['Free Spins', 'Expanding Symbols', '10 Paylines'],
    paylines: 10,
    reels: 5
  },
  {
    id: 'golden-goddess',
    name: 'Golden Goddess',
    slug: 'golden-goddess',
    description: 'Ancient Greek mythology meets modern slot gaming.',
    thumbnail: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'IGT',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 20,
    maxBet: 8000,
    jackpot: 80000,
    rtp: 96.00,
    volatility: 'medium',
    features: ['Super Stacks', 'Free Spins', 'Wild'],
    paylines: 40,
    reels: 5
  },
  {
    id: 'cleopatra',
    name: 'Cleopatra',
    slug: 'cleopatra',
    description: 'The queen of Egypt awaits with treasures beyond imagination.',
    thumbnail: 'https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'IGT',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 6000,
    jackpot: 60000,
    rtp: 95.02,
    volatility: 'medium',
    features: ['Free Spins', 'Multiplier', 'Sphinx Bonus'],
    paylines: 20,
    reels: 5
  },
  {
    id: 'pharaohs-gold',
    name: "Pharaoh's Gold",
    slug: 'pharaohs-gold',
    description: 'Unlock the secrets of the pyramids and claim the pharaohs gold.',
    thumbnail: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: true,
    isPopular: false,
    minBet: 10,
    maxBet: 4000,
    jackpot: 40000,
    rtp: 95.50,
    volatility: 'medium',
    features: ['Free Spins', 'Scatter', 'Wild'],
    paylines: 9,
    reels: 5
  },
  {
    id: 'fruits-n-sevens',
    name: 'Fruits n Sevens',
    slug: 'fruits-n-sevens',
    description: 'Classic fruit machine with a modern twist and big jackpot.',
    thumbnail: 'https://images.unsplash.com/photo-1566818013954-4ab6c4bd3a06?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1566818013954-4ab6c4bd3a06?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: false,
    isPopular: false,
    minBet: 5,
    maxBet: 1000,
    jackpot: 10000,
    rtp: 94.00,
    volatility: 'low',
    features: ['Progressive Jackpot', 'Classic Symbols'],
    paylines: 5,
    reels: 5
  },
  {
    id: 'ultra-hot',
    name: 'Ultra Hot',
    slug: 'ultra-hot',
    description: 'Feel the heat with this fiery classic slot game.',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 3000,
    jackpot: 30000,
    rtp: 95.81,
    volatility: 'low',
    features: ['Stacked Symbols', 'Gamble'],
    paylines: 5,
    reels: 3
  },
  {
    id: 'magic-star',
    name: 'Magic Star',
    slug: 'magic-star',
    description: 'Magical wins await among the stars in this enchanting slot.',
    thumbnail: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: true,
    isPopular: false,
    minBet: 10,
    maxBet: 2000,
    jackpot: 20000,
    rtp: 95.00,
    volatility: 'medium',
    features: ['Free Spins', 'Wild Multiplier'],
    paylines: 10,
    reels: 5
  },
  // CASINO GAMES
  {
    id: 'american-poker',
    name: 'American Poker',
    slug: 'american-poker',
    description: 'Classic video poker with American rules and great payouts.',
    thumbnail: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=1200&h=400&fit=crop',
    category: 'casino',
    provider: 'Novomatic',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 5000,
    rtp: 98.00,
    volatility: 'low',
    features: ['Jacks or Better', 'Double Up', 'Bonus Rounds']
  },
  {
    id: 'european-roulette',
    name: 'European Roulette',
    slug: 'european-roulette',
    description: 'The classic European roulette with single zero for better odds.',
    thumbnail: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=1200&h=400&fit=crop',
    category: 'casino',
    provider: 'Evolution',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 10000,
    rtp: 97.30,
    volatility: 'medium',
    features: ['Single Zero', 'European Rules', 'Neighbor Bets']
  },
  {
    id: 'blackjack-classic',
    name: 'Blackjack Classic',
    slug: 'blackjack-classic',
    description: 'Beat the dealer in this classic casino card game.',
    thumbnail: 'https://images.unsplash.com/photo-1541278107931-e006523892df?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1541278107931-e006523892df?w=1200&h=400&fit=crop',
    category: 'casino',
    provider: 'Evolution',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 5000,
    rtp: 99.50,
    volatility: 'low',
    features: ['Double Down', 'Split', 'Insurance']
  },
  {
    id: 'baccarat',
    name: 'Baccarat',
    slug: 'baccarat',
    description: 'The game of choice for high rollers around the world.',
    thumbnail: 'https://images.unsplash.com/photo-1596838132731-3301c3a431be?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1596838132731-3301c3a431be?w=1200&h=400&fit=crop',
    category: 'casino',
    provider: 'Evolution',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 100,
    maxBet: 20000,
    rtp: 98.94,
    volatility: 'low',
    features: ['Player/Banker Bets', 'Tie Bet', 'No Commission']
  },
  {
    id: 'texas-holdem',
    name: 'Texas Holdem Poker',
    slug: 'texas-holdem',
    description: 'The most popular poker variant in the world.',
    thumbnail: 'https://images.unsplash.com/photo-1609743522653-52354461eb27?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1609743522653-52354461eb27?w=1200&h=400&fit=crop',
    category: 'poker',
    provider: 'GameTwist',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 50,
    maxBet: 10000,
    rtp: 97.50,
    volatility: 'medium',
    features: ['Multi-table', 'Tournaments', 'Cash Games']
  },
  {
    id: 'omaha-poker',
    name: 'Omaha Poker',
    slug: 'omaha-poker',
    description: 'Four hole cards create more action in this exciting variant.',
    thumbnail: 'https://images.unsplash.com/photo-1513842502528-5d6d7c408c4d?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1513842502528-5d6d7c408c4d?w=1200&h=400&fit=crop',
    category: 'poker',
    provider: 'GameTwist',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 50,
    maxBet: 5000,
    rtp: 97.00,
    volatility: 'medium',
    features: ['4 Hole Cards', 'Pot Limit', 'Hi-Lo']
  },
  // SKILL GAMES
  {
    id: 'pool',
    name: '8-Ball Pool',
    slug: 'pool',
    description: 'Test your skills in this realistic pool simulation.',
    thumbnail: 'https://images.unsplash.com/photo-1615722552605-8d2eb1a5b2e2?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1615722552605-8d2eb1a5b2e2?w=1200&h=400&fit=crop',
    category: 'skill',
    provider: 'GameTwist',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    minBet: 20,
    maxBet: 2000,
    volatility: 'low',
    features: ['8-Ball Rules', 'Multiplayer', 'Tournaments']
  },
  {
    id: 'solitaire',
    name: 'Solitaire',
    slug: 'solitaire',
    description: 'The classic card game with modern features.',
    thumbnail: 'https://images.unsplash.com/photo-1541278107931-e006523892df?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1541278107931-e006523892df?w=1200&h=400&fit=crop',
    category: 'skill',
    provider: 'GameTwist',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 10,
    maxBet: 500,
    volatility: 'low',
    features: ['Klondike', 'Vegas Rules', 'Statistics']
  },
  {
    id: 'mahjong',
    name: 'Mahjong',
    slug: 'mahjong',
    description: 'Ancient Chinese tile game of skill and strategy.',
    thumbnail: 'https://images.unsplash.com/photo-1605870445919-838d190e8e1b?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1605870445919-838d190e8e1b?w=1200&h=400&fit=crop',
    category: 'skill',
    provider: 'GameTwist',
    isFeatured: false,
    isNew: true,
    isPopular: false,
    minBet: 20,
    maxBet: 1000,
    volatility: 'medium',
    features: ['Mahjong Solitaire', 'Multiple Layouts', 'Hints']
  },
  {
    id: 'dominoes',
    name: 'Dominoes',
    slug: 'dominoes',
    description: 'Classic dominoes game with multiple variants.',
    thumbnail: 'https://images.unsplash.com/photo-1585435421671-0c16764628ce?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1585435421671-0c16764628ce?w=1200&h=400&fit=crop',
    category: 'skill',
    provider: 'GameTwist',
    isFeatured: false,
    isNew: false,
    isPopular: false,
    minBet: 10,
    maxBet: 500,
    volatility: 'low',
    features: ['Classic Rules', 'Multiplayer', 'Tournaments']
  },
  {
    id: 'yatzy',
    name: 'Yatzy',
    slug: 'yatzy',
    description: 'Roll the dice and score big in this classic dice game.',
    thumbnail: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=1200&h=400&fit=crop',
    category: 'skill',
    provider: 'GameTwist',
    isFeatured: false,
    isNew: false,
    isPopular: false,
    minBet: 10,
    maxBet: 300,
    volatility: 'low',
    features: ['5 Dice', 'Scoreboard', 'Multiplayer']
  },
  {
    id: 'backgammon',
    name: 'Backgammon',
    slug: 'backgammon',
    description: 'One of the oldest board games in history.',
    thumbnail: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=1200&h=400&fit=crop',
    category: 'skill',
    provider: 'GameTwist',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 20,
    maxBet: 1000,
    volatility: 'medium',
    features: ['Classic Rules', 'Doubling Cube', 'Multiplayer']
  },
  // BINGO
  {
    id: 'bingo-classic',
    name: 'Bingo Classic',
    slug: 'bingo-classic',
    description: 'Classic 90-ball bingo with big prizes.',
    thumbnail: 'https://images.unsplash.com/photo-1566818013954-4ab6c4bd3a06?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1566818013954-4ab6c4bd3a06?w=1200&h=400&fit=crop',
    category: 'bingo',
    provider: 'GameTwist',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    minBet: 5,
    maxBet: 200,
    volatility: 'low',
    features: ['90 Ball', 'Pattern Bingo', 'Jackpot']
  },
  {
    id: 'bingo-blitz',
    name: 'Bingo Blitz',
    slug: 'bingo-blitz',
    description: 'Fast-paced bingo action with power-ups.',
    thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=400&fit=crop',
    category: 'bingo',
    provider: 'GameTwist',
    isFeatured: true,
    isNew: true,
    isPopular: true,
    minBet: 10,
    maxBet: 500,
    volatility: 'medium',
    features: ['Power-ups', 'Collection', 'Multi-room']
  },
  // MORE SLOTS
  {
    id: 'gryphons-gold',
    name: "Griffin's Gold",
    slug: 'gryphons-gold',
    description: 'Mythical creatures guard golden treasures.',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: true,
    isPopular: false,
    minBet: 10,
    maxBet: 3000,
    jackpot: 30000,
    rtp: 95.00,
    volatility: 'medium',
    features: ['Free Spins', 'Wild Griffin', 'Scatter'],
    paylines: 10,
    reels: 5
  },
  {
    id: 'just-jewels',
    name: 'Just Jewels',
    slug: 'just-jewels',
    description: 'Dazzling gems and jewels bring sparkling wins.',
    thumbnail: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: false,
    isPopular: false,
    minBet: 10,
    maxBet: 2000,
    jackpot: 20000,
    rtp: 95.42,
    volatility: 'low',
    features: ['Win Both Ways', 'Scatter Pays'],
    paylines: 9,
    reels: 5
  },
  {
    id: 'magic-kingdom',
    name: 'Magic Kingdom',
    slug: 'magic-kingdom',
    description: 'Enter a magical realm of fantasy and fortune.',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: false,
    isPopular: false,
    minBet: 20,
    maxBet: 4000,
    jackpot: 40000,
    rtp: 95.10,
    volatility: 'medium',
    features: ['Free Games', 'Magic Bonus', 'Wild Dragon'],
    paylines: 25,
    reels: 5
  },
  {
    id: 'captain-treasure',
    name: 'Captain Treasure',
    slug: 'captain-treasure',
    description: 'Sail the seas in search of pirate gold.',
    thumbnail: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Novomatic',
    isFeatured: false,
    isNew: false,
    isPopular: false,
    minBet: 10,
    maxBet: 3000,
    jackpot: 30000,
    rtp: 94.90,
    volatility: 'medium',
    features: ['Treasure Bonus', 'Free Spins', 'Wild Captain'],
    paylines: 15,
    reels: 5
  },
  {
    id: 'wild-west-gold',
    name: 'Wild West Gold',
    slug: 'wild-west-gold',
    description: 'Saddle up for big wins in the wild frontier.',
    thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Pragmatic',
    isFeatured: true,
    isNew: true,
    isPopular: true,
    minBet: 20,
    maxBet: 8000,
    jackpot: 80000,
    rtp: 96.51,
    volatility: 'high',
    features: ['Sticky Wilds', 'Free Spins', 'Multipliers'],
    paylines: 40,
    reels: 5
  },
  {
    id: 'gates-of-olympus',
    name: 'Gates of Olympus',
    slug: 'gates-of-olympus',
    description: 'Zeus opens the gates to divine winnings.',
    thumbnail: 'https://images.unsplash.com/photo-1568702846914-96b305d2uj9d?w=400&h=300&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1568702846914-96b305d2uj9d?w=1200&h=400&fit=crop',
    category: 'slots',
    provider: 'Pragmatic',
    isFeatured: true,
    isNew: true,
    isPopular: true,
    minBet: 20,
    maxBet: 10000,
    jackpot: 500000,
    rtp: 96.50,
    volatility: 'high',
    features: ['Tumble Feature', 'Multipliers', 'Free Spins'],
    paylines: 0,
    reels: 6
  }
];

export const gameCategories = [
  { id: 'slots', name: 'Slots', icon: '🎰', count: 16 },
  { id: 'casino', name: 'Casino', icon: '🎲', count: 4 },
  { id: 'poker', name: 'Poker', icon: '🃏', count: 2 },
  { id: 'skill', name: 'Skill Games', icon: '🎯', count: 6 },
  { id: 'bingo', name: 'Bingo', icon: '🎱', count: 2 },
  { id: 'novoline', name: 'Novoline', icon: '⭐', count: 12 }
];

export const featuredGames = gamesData.filter(g => g.isFeatured);
export const popularGames = gamesData.filter(g => g.isPopular);
export const newGames = gamesData.filter(g => g.isNew);
